codecov:
  require_ci_to_pass: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true
  hide_project_coverage: false # [true :: only show coverage on the git diff aka patch coverage]]

coverage:
  precision: 2
  round: down
  range: 85...100

  status:
    project:
      default:
        target: 100%
        threshold: 1%
        base: auto
        informational: true
    patch:
      default:
        informational: true

#flags:
#  pest:
#    paths:
#      - tests/
#    carryforward: false
#
#codecov_yml_version: 2.1
