FROM php:8.4.2-cli-alpine3.20

COPY --from=composer:2.7.4 /usr/bin/composer /usr/bin/

RUN \
    set -ex && \
    apk update && \
    apk add --no-cache libstdc++ libpq && \
    apk add --no-cache --virtual .build-deps $PHPIZE_DEPS curl-dev linux-headers postgresql-dev openssl-dev pcre-dev pcre2-dev zlib-dev && \
    apk add --no-cache supervisor && \
    apk add --no-cache supercronic && \
#    apk add --no-cache certbot && \
    pecl channel-update pecl.php.net && \
    docker-php-ext-install sockets && \
    pecl install redis &&  \
    docker-php-ext-enable redis && \
    pecl install xdebug && \
    docker-php-ext-enable xdebug && \
    docker-php-source extract && \
    mkdir /usr/src/php/ext/swoole && \
    curl -sfL https://github.com/swoole/swoole-src/archive/v6.0.0.tar.gz -o swoole.tar.gz && \
    tar xfz swoole.tar.gz --strip-components=1 -C /usr/src/php/ext/swoole && \
    docker-php-ext-configure swoole \
        --enable-swoole-pgsql \
        --enable-openssl      \
        --enable-sockets --enable-swoole-curl && \
    docker-php-ext-install -j$(nproc) swoole && \
    docker-php-ext-configure pcntl --enable-pcntl && \
    docker-php-ext-install pcntl && \
    rm -f swoole.tar.gz && \
    docker-php-source delete && \
    apk del .build-deps

RUN apk add --no-cache nodejs npm git
RUN npm install yarn -g

#RUN certbot --staging certonly --standalone -d mentor-wizard.com --email mentor.wizard.ua@gmail.com --agree-tos --non-interactive

COPY docker/php/supervisord/supervisord.conf /etc/

EXPOSE 8000

WORKDIR "/var/www/"

ENTRYPOINT ["supervisord", "--nodaemon", "--configuration", "/etc/supervisord.conf"]
