name: mentor-wizard
type: laravel
docroot: public
database:
  type: postgres
  version: '17'
php_version: '8.4'
host_db_port: '33371'
nodejs_version: '22'
webserver_type: nginx-fpm
xdebug_enabled: false
corepack_enable: true
webimage_extra_packages:
  - 'php${DDEV_PHP_VERSION}-swoole'
web_extra_daemons:
  - name: 'octane'
    command: 'php artisan octane:start --watch --host=0.0.0.0 --port=8000'
    directory: /var/www/html
  - name: 'vite'
    command: 'yarn install && yarn dev'
    directory: /var/www/html
web_extra_exposed_ports:
  - name: 'octane'
    container_port: 8000
    http_port: 8001
    https_port: 8000
  - name: 'vite'
    container_port: 5173
    http_port: 5172
    https_port: 5173
hooks:
  pre-start:
    # Add redis, cron and task to ddev if not already installed.
    - exec-host: |
        ddev add-on list --installed | grep -q 'ddev/ddev-cron' || ddev add-on get ddev/ddev-cron  > /dev/null
        ddev add-on list --installed | grep -q 'ddev/ddev-redis' || ddev add-on get ddev/ddev-redis > /dev/null
        ddev add-on list --installed | grep -q 'gebruederheitz/ddev-taskfile' || ddev add-on get gebruederheitz/ddev-taskfile > /dev/null
  post-start:
    - composer: install
  post-import-db:
    - exec: php artisan migrate --force --ansi
